openapi: 3.0.1
info:
  title: Dobie
  x-cortex-tag: Dobie
  x-cortex-git:
    github:
      repository: cremerica/Dobie
  x-cortex-custom-metadata:
    cortex-template-version: 1.0
    cortex-generated-timestamp: 2024-03-29T17:42:01.548819347
